### PR TITLE
Migrate from buildkite to github actions

### PR DESCRIPTION
**Pull request by strokovok**

### CODE REVIEW

**Review by chefsale — APPROVED** [review]
Probably we want to delete the buildkite folder as well?

**Comment by strokovok** [comment]
> Probably we want to delete the buildkite folder as well?

Yep, but when I delete it, the check is still here, and it's failing with "unable to find .buildkite". Do you know how can we get rid of it?

**Review by sept-en — APPROVED** [review]
LGTM!

**Comment by chefsale** [comment]
I will delete the pipeline in that case. I think it should disappear than.

**Comment by chefsale** [comment]
Deleted all the eth-connector pipelines now, please retry.

**Pull request merged**
